import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { FooterNew, HeaderNew } from "../../libs/common/ui";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
   // images:'path/to/image'
  openGraph:{
    title:'SEO TITLE EXAMPLE',
    description:"SEO DESC EXAMPLE",
    // images:'path/to/image'

  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <HeaderNew />
        <main>
            {children}
        </main>
      
        <FooterNew />
        
        </body>
    </html>
  );
}

